version: "2"
linters:
  default: none
  enable:
    - govet
    - staticcheck
  exclusions:
    rules:
      - path: cmd/zincsearch/main.go
        text: SA1019
      - path: pkg/uquery/query/query.go
        text: SA4023
formatters:
  enable:
    - gofmt
