name: Zinc actions
on: [ pull_request ]
jobs:
  Codecov-coverage:
    runs-on: ubuntu-latest
    env:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: Complexpass#123
      ZINC_WAL_SYNC_INTERVAL: 10ms
      ZINC_WAL_REDOLOG_NO_SYNC: true
      ZINC_WAL_ENABLE: false
      ZINC_ENABLE_TEXT_KEYWORD_MAPPING: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: cd web && npm i && npm run build && cd ..

      - uses: actions/setup-go@v3
        with:
          go-version: "1.24"
          check-latest: true
      - run: go install honnef.co/go/tools/cmd/staticcheck@v0.6.1

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.25.1'

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: install faiss
        run: |
            bash -e ./ci/install_faiss.sh

      - name: Static Check
        run: |
          [ "$(gofmt -l . 2>&1)" == "" ]
          go vet
          staticcheck ./...

      - run: go test ./... -race -covermode=atomic -coverprofile=coverage.out
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
